type: dagster_component_templates.TicketClassifierComponent
attributes:
  asset_name: classified_support_tickets

  # Classification Method
  method: llm  # Options: llm, transformer

  # LLM Configuration (for method=llm)
  llm_provider: openai  # Options: openai, anthropic
  llm_model: gpt-4o-mini  # Options: gpt-4o-mini, gpt-4, claude-3-haiku, claude-3-5-sonnet
  api_key: "${OPENAI_API_KEY}"

  # Transformer Configuration (for method=transformer)
  # transformer_model: bert-base-uncased

  # Input Configuration
  input_column: ticket_text

  # Classification Categories
  categories: "technical,billing,account,product,general,other"
  urgency_levels: "low,medium,high,critical"
  departments: "engineering,finance,customer_success,sales,operations"

  # Optional Features
  classify_sentiment: true
  include_confidence: true
  include_reasoning: false
  multi_label: false

  # Confidence Filtering
  confidence_threshold: 0.7

  # Processing Configuration
  batch_size: 50
  temperature: 0.0
  max_tokens: 200

  # Performance & Costs
  rate_limit_delay: 0.1
  max_retries: 3
  enable_caching: true
  track_costs: true

  # Optional: Include metadata fields in classification
  # include_metadata_fields: "customer_tier,channel"

  # Organization
  description: "Support ticket classification with urgency and department routing"
  group_name: "ticket_classification"
  include_sample_metadata: true
