"""Weights & Biases Asset Component.

Logs metrics, artifacts, and model checkpoints to Weights & Biases.

Supports two modes:
- ``log_metrics``: reads metrics from a source database table and logs each row as
  a W&B run step.
- ``log_artifact``: uploads a local file or directory as a W&B artifact.
"""
from __future__ import annotations

from typing import Optional

import dagster as dg


class WandbAssetComponent(dg.Component, dg.Model, dg.Resolvable):
    """Log metrics or upload artifacts to Weights & Biases.

    Set ``mode`` to ``"log_metrics"`` to stream rows from a database table into a W&B
    run, or to ``"log_artifact"`` to upload a file/directory as a W&B artifact.

    Example:
        ```yaml
        type: dagster_component_templates.WandbAssetComponent
        attributes:
          asset_name: model_training_run
          project: churn-prediction
          entity: my-team
          mode: log_metrics
          wandb_api_key_env_var: WANDB_API_KEY
          database_url_env_var: DATABASE_URL
          source_table: model_training_results
          metrics_columns:
            - train_loss
            - val_loss
            - accuracy
          step_column: epoch
          tags:
            - production
            - v2
          group_name: ml_tracking
          deps:
            - marts/training_data
        ```
    """

    wandb_api_key_env_var: str = dg.Field(
        default="WANDB_API_KEY",
        description="Environment variable name holding the W&B API key.",
    )
    project: str = dg.Field(description="W&B project name to log runs into.")
    entity: Optional[str] = dg.Field(
        default=None,
        description="W&B entity (team or username). Defaults to the API-key owner.",
    )
    run_name: Optional[str] = dg.Field(
        default=None,
        description="W&B run name. Auto-generated by W&B when None.",
    )
    mode: str = dg.Field(
        default="log_metrics",
        description='Operation mode: "log_metrics" or "log_artifact".',
    )
    database_url_env_var: Optional[str] = dg.Field(
        default=None,
        description="Env var with SQLAlchemy DB URL. Required for log_metrics mode.",
    )
    source_table: Optional[str] = dg.Field(
        default=None,
        description="Table whose rows are logged as W&B metrics. Required for log_metrics mode.",
    )
    metrics_columns: Optional[list] = dg.Field(
        default=None,
        description="Specific columns to log. None logs all numeric columns.",
    )
    step_column: Optional[str] = dg.Field(
        default=None,
        description="Column to use as the W&B step/epoch number.",
    )
    artifact_path: Optional[str] = dg.Field(
        default=None,
        description="Local file or directory path to upload. Required for log_artifact mode.",
    )
    artifact_name: Optional[str] = dg.Field(
        default=None,
        description="Artifact name in W&B. Defaults to the basename of artifact_path.",
    )
    artifact_type: str = dg.Field(
        default="dataset",
        description='W&B artifact type, e.g. "dataset", "model", "evaluation".',
    )
    tags: Optional[list] = dg.Field(
        default=None,
        description="List of string tags to attach to the W&B run.",
    )
    group_name: Optional[str] = dg.Field(
        default="ml_tracking",
        description="Dagster asset group name shown in the UI.",
    )
    asset_name: str = dg.Field(description="Dagster asset key name.")
    deps: Optional[list] = dg.Field(
        default=None,
        description="Upstream asset keys for lineage.",
    )

    def build_defs(self, context: dg.ComponentLoadContext) -> dg.Definitions:
        dep_keys = [dg.AssetKey.from_user_string(k) for k in (self.deps or [])]

        @dg.asset(
            name=self.asset_name,
            group_name=self.group_name or "ml_tracking",
            kinds={"wandb", "ml"},
            deps=dep_keys,
            description=(
                f"W&B {self.mode} asset — project: {self.project}"
            ),
        )
        def _wandb_asset(context: dg.AssetExecutionContext) -> dg.MaterializeResult:
            import os
            import wandb

            api_key = os.environ[self.wandb_api_key_env_var]
            wandb.login(key=api_key)

            run = wandb.init(
                project=self.project,
                entity=self.entity,
                name=self.run_name,
                tags=self.tags or [],
                group=self.group_name,
            )

            try:
                if self.mode == "log_metrics":
                    if not self.database_url_env_var or not self.source_table:
                        raise ValueError(
                            "database_url_env_var and source_table are required for log_metrics mode."
                        )
                    from sqlalchemy import create_engine, text

                    db_url = os.environ[self.database_url_env_var]
                    engine = create_engine(db_url)
                    with engine.connect() as conn:
                        result = conn.execute(text(f"SELECT * FROM {self.source_table}"))
                        rows = result.fetchall()
                        columns = list(result.keys())

                    if self.metrics_columns:
                        col_set = set(self.metrics_columns)
                        if self.step_column:
                            col_set.add(self.step_column)
                        columns_to_log = [c for c in columns if c in col_set]
                    else:
                        columns_to_log = columns

                    rows_logged = 0
                    for row in rows:
                        row_dict = dict(zip(columns, row))
                        step = None
                        if self.step_column and self.step_column in row_dict:
                            step = int(row_dict[self.step_column])

                        metrics = {
                            k: v
                            for k, v in row_dict.items()
                            if k in columns_to_log and k != self.step_column and isinstance(v, (int, float))
                        }
                        run.log(metrics, step=step)
                        rows_logged += 1

                    context.log.info(f"Logged {rows_logged} rows to W&B run {run.id}")

                elif self.mode == "log_artifact":
                    import os as _os

                    if not self.artifact_path:
                        raise ValueError("artifact_path is required for log_artifact mode.")

                    name = self.artifact_name or _os.path.basename(self.artifact_path.rstrip("/"))
                    artifact = wandb.Artifact(name=name, type=self.artifact_type)

                    if _os.path.isdir(self.artifact_path):
                        artifact.add_dir(self.artifact_path)
                    else:
                        artifact.add_file(self.artifact_path)

                    run.log_artifact(artifact)
                    context.log.info(f"Uploaded artifact '{name}' to W&B run {run.id}")

                else:
                    raise ValueError(f"Unknown mode '{self.mode}'. Must be 'log_metrics' or 'log_artifact'.")

            finally:
                run.finish()

            return dg.MaterializeResult(
                metadata={
                    "run_id": dg.MetadataValue.text(run.id),
                    "project": dg.MetadataValue.text(self.project),
                    "run_url": dg.MetadataValue.url(run.get_url() or ""),
                    "mode": dg.MetadataValue.text(self.mode),
                }
            )

        return dg.Definitions(assets=[_wandb_asset])
