"""Weights & Biases Asset Component.

Logs metrics, artifacts, and model checkpoints to Weights & Biases.

Supports two modes:
- ``log_metrics``: accepts a DataFrame from an upstream Dagster asset and logs each
  row as a W&B run step.
- ``log_artifact``: uploads a local file or directory as a W&B artifact.
"""
from __future__ import annotations

from typing import Optional

import dagster as dg
from pydantic import Field


class WandbAssetComponent(dg.Component, dg.Model, dg.Resolvable):
    """Log metrics or upload artifacts to Weights & Biases.

    Set ``mode`` to ``"log_metrics"`` to stream rows from an upstream Dagster asset
    DataFrame into a W&B run, or to ``"log_artifact"`` to upload a file/directory
    as a W&B artifact.

    Example:
        ```yaml
        type: dagster_component_templates.WandbAssetComponent
        attributes:
          asset_name: model_training_run
          project: churn-prediction
          entity: my-team
          mode: log_metrics
          upstream_asset_key: marts/training_data
          wandb_api_key_env_var: WANDB_API_KEY
          metrics_columns:
            - train_loss
            - val_loss
            - accuracy
          step_column: epoch
          tags:
            - production
            - v2
          group_name: ml_tracking
        ```
    """

    asset_name: str = Field(description="Dagster asset key name.")
    upstream_asset_key: str = Field(
        description=(
            "Asset key of the upstream asset providing a pandas DataFrame. "
            "In ``log_metrics`` mode, each row is logged as a W&B run step. "
            "In ``log_artifact`` mode, this field is used for lineage only."
        )
    )
    wandb_api_key_env_var: str = Field(
        default="WANDB_API_KEY",
        description="Environment variable name holding the W&B API key.",
    )
    project: str = Field(description="W&B project name to log runs into.")
    entity: Optional[str] = Field(
        default=None,
        description="W&B entity (team or username). Defaults to the API-key owner.",
    )
    run_name: Optional[str] = Field(
        default=None,
        description="W&B run name. Auto-generated by W&B when None.",
    )
    mode: str = Field(
        default="log_metrics",
        description='Operation mode: "log_metrics" or "log_artifact".',
    )
    metrics_columns: Optional[list] = Field(
        default=None,
        description="Specific columns to log. None logs all numeric columns.",
    )
    step_column: Optional[str] = Field(
        default=None,
        description="Column to use as the W&B step/epoch number.",
    )
    artifact_path: Optional[str] = Field(
        default=None,
        description="Local file or directory path to upload. Required for log_artifact mode.",
    )
    artifact_name: Optional[str] = Field(
        default=None,
        description="Artifact name in W&B. Defaults to the basename of artifact_path.",
    )
    artifact_type: str = Field(
        default="dataset",
        description='W&B artifact type, e.g. "dataset", "model", "evaluation".',
    )
    tags: Optional[list] = Field(
        default=None,
        description="List of string tags to attach to the W&B run.",
    )
    group_name: Optional[str] = Field(
        default="ml_tracking",
        description="Dagster asset group name shown in the UI.",
    )
    partition_type: Optional[str] = Field(
        default=None,
        description="Partition type: 'daily', 'weekly', 'monthly', 'hourly', 'static', 'multi', or None for unpartitioned",
    )
    partition_start: Optional[str] = Field(
        default=None,
        description="Partition start date in ISO format, e.g. '2024-01-01'. Required for time-based partition types.",
    )
    partition_date_column: Optional[str] = Field(
        default=None,
        description="Column used to filter upstream DataFrame to the current date partition key.",
    )
    partition_values: Optional[str] = Field(
        default=None,
        description="Comma-separated values for static or multi partitioning, e.g. 'customer_a,customer_b,customer_c'.",
    )
    partition_static_dim: Optional[str] = Field(
        default=None,
        description="Dimension name for the static axis in multi-partitioning, e.g. 'customer' or 'region'.",
    )
    partition_static_column: Optional[str] = Field(
        default=None,
        description="Column used to filter upstream DataFrame to the current static partition dimension (e.g. 'customer_id').",
    )

    def build_defs(self, context: dg.ComponentLoadContext) -> dg.Definitions:
        component = self

        @dg.asset(
            name=component.asset_name,
            group_name=component.group_name or "ml_tracking",
            kinds={"wandb", "ml"},
            ins={"upstream": dg.AssetIn(key=dg.AssetKey.from_user_string(component.upstream_asset_key))},
            description=(
                f"W&B {component.mode} asset — project: {component.project}"
            ),
        )
        def _wandb_asset(
            context: dg.AssetExecutionContext,
            upstream,
        ) -> dg.MaterializeResult:
            import os
            import wandb

            api_key = os.environ[component.wandb_api_key_env_var]
            wandb.login(key=api_key)

            run = wandb.init(
                project=component.project,
                entity=component.entity,
                name=component.run_name,
                tags=component.tags or [],
                group=component.group_name,
            )

            try:
                if component.mode == "log_metrics":
                    import pandas as pd  # type: ignore[import]

                    df = upstream
                    if not isinstance(df, pd.DataFrame):
                        raise ValueError("Upstream asset did not provide a pandas DataFrame.")

                    context.log.info(f"[W&B] Logging {len(df)} rows to run {run.id}")

                    columns = list(df.columns)
                    if component.metrics_columns:
                        col_set = set(component.metrics_columns)
                        if component.step_column:
                            col_set.add(component.step_column)
                        columns_to_log = [c for c in columns if c in col_set]
                    else:
                        columns_to_log = columns

                    rows_logged = 0
                    for _, row in df.iterrows():
                        row_dict = row.to_dict()
                        step = None
                        if component.step_column and component.step_column in row_dict:
                            step = int(row_dict[component.step_column])

                        metrics = {
                            k: v
                            for k, v in row_dict.items()
                            if k in columns_to_log
                            and k != component.step_column
                            and isinstance(v, (int, float))
                        }
                        run.log(metrics, step=step)
                        rows_logged += 1

                    context.log.info(f"[W&B] Logged {rows_logged} rows to run {run.id}")

                elif component.mode == "log_artifact":
                    import os as _os

                    if not component.artifact_path:
                        raise ValueError("artifact_path is required for log_artifact mode.")

                    name = component.artifact_name or _os.path.basename(
                        component.artifact_path.rstrip("/")
                    )
                    artifact = wandb.Artifact(name=name, type=component.artifact_type)

                    if _os.path.isdir(component.artifact_path):
                        artifact.add_dir(component.artifact_path)
                    else:
                        artifact.add_file(component.artifact_path)

                    run.log_artifact(artifact)
                    context.log.info(f"[W&B] Uploaded artifact '{name}' to run {run.id}")

                else:
                    raise ValueError(
                        f"Unknown mode '{component.mode}'. Must be 'log_metrics' or 'log_artifact'."
                    )

            finally:
                run.finish()

            return dg.MaterializeResult(
                metadata={
                    "run_id": dg.MetadataValue.text(run.id),
                    "project": dg.MetadataValue.text(component.project),
                    "run_url": dg.MetadataValue.url(run.get_url() or ""),
                    "mode": dg.MetadataValue.text(component.mode),
                }
            )

        return dg.Definitions(assets=[_wandb_asset])
