synthetic_commerce_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DESIGNER_PROJECT_DATA_DIR', '../../data') }}/synthetic_commerce.duckdb"
      schema: main
      threads: 1
