"""Normalize component README structure to match dataframe_to_csv's shape.

Three mechanical transformations (no prose touched):

  1. Heading rename: `## Description` / `## Overview` → `## Purpose`
  2. Heading rename: `## Example` → `## Example YAML`
  3. Move the auto-generated FIELDS block (between
     <!-- FIELDS:START --> and <!-- FIELDS:END --> markers) to land
     immediately after the intro H2 (`## Purpose`, or the first H2 if
     none) and its prose body. Today the block often sits at the end of
     the README, which buries it under marketing-style sections.

Idempotent: re-running on already-normalized READMEs is a no-op.

Run:
    python3 tools/normalize_readme_structure.py             # all READMEs
    python3 tools/normalize_readme_structure.py --dry-run   # diff only
    python3 tools/normalize_readme_structure.py --only PATH...
"""
import argparse
import re
import sys
from pathlib import Path
from typing import Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent

START_MARKER = "<!-- FIELDS:START - auto-generated by tools/regen_readme_fields.py -->"
END_MARKER = "<!-- FIELDS:END -->"

INTRO_RENAMES = {
    r"^## Description\b": "## Purpose",
    r"^## Overview\b": "## Purpose",
}
EXAMPLE_RENAMES = {
    # Only rename when it's a plain `## Example` (not `## Example YAML` or
    # `## Example use cases` or `## Examples` plural). Plural stays as-is —
    # multi-example READMEs are legitimate.
    r"^## Example\s*$": "## Example YAML",
    r"^## Example:\s*$": "## Example YAML",
}


def apply_renames(text: str) -> tuple[str, int]:
    """Apply heading-rename rules. Returns (new_text, n_changes)."""
    n = 0
    for pattern, replacement in {**INTRO_RENAMES, **EXAMPLE_RENAMES}.items():
        new, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
        n += count
        text = new
    return text, n


def find_fields_block(text: str) -> Optional[Tuple[int, int]]:
    """Locate the auto-Fields block. Returns (start_offset, end_offset) of
    the block including markers and surrounding blank lines, or None."""
    s = text.find(START_MARKER)
    e = text.find(END_MARKER)
    if s < 0 or e < 0 or e <= s:
        return None
    block_end = e + len(END_MARKER)
    # Extend back to absorb a single leading blank line (so removing leaves
    # one clean blank between adjacent sections).
    start = s
    if start > 0 and text[start - 1] == "\n":
        start -= 1
        if start > 0 and text[start - 1] == "\n":
            start -= 1
    # Extend forward to absorb a single trailing newline.
    end = block_end
    if end < len(text) and text[end] == "\n":
        end += 1
    return (start, end)


def find_intro_anchor(text: str) -> Optional[int]:
    """Find the byte offset AT WHICH to insert the FIELDS block.

    Prefers `## Purpose` — insert right before the H2 that follows the
    Purpose section's body. If no `## Purpose` exists, falls back to the
    first H2 in the document.
    Returns None if no H2s found.
    """
    # Match the first `## Purpose` heading.
    purpose = re.search(r"^## Purpose\b.*$", text, re.MULTILINE)
    if purpose:
        # Find the NEXT H2 after Purpose. Insert right before it.
        next_h2 = re.search(r"^## (?!Purpose\b)", text[purpose.end():], re.MULTILINE)
        if next_h2:
            return purpose.end() + next_h2.start()
        # No following H2 → Purpose is the last section. Append at EOF.
        return len(text.rstrip()) + 1 if text.rstrip() else 0

    # Fall back: insert before the second H2 (after the first/intro one).
    h2s = list(re.finditer(r"^## ", text, re.MULTILINE))
    if len(h2s) >= 2:
        return h2s[1].start()
    if len(h2s) == 1:
        # Only one H2; insert at end.
        return len(text.rstrip()) + 1 if text.rstrip() else 0
    return None


def move_fields_block(text: str) -> Tuple[str, bool]:
    """Move the FIELDS block to right after the intro section. Returns
    (new_text, moved).

    Only moves when the FIELDS block is currently the last section of the
    README (no H2 appears after the END marker). If any H2 follows FIELDS,
    the author has deliberately placed FIELDS in mid-document order — don't
    second-guess them. This preserves carefully-structured READMEs like
    precisely_run_asset where Connection / API-verification sections sit
    between the intro and the FIELDS block on purpose.
    """
    loc = find_fields_block(text)
    if loc is None:
        return text, False
    block_start, block_end = loc

    # Bail if any H2 follows the FIELDS block — author put it mid-document.
    tail = text[block_end:]
    if re.search(r"^## ", tail, re.MULTILINE):
        return text, False

    anchor = find_intro_anchor(text)
    if anchor is None:
        return text, False
    # If the block is already in the right place — i.e. its start sits at
    # the anchor (allowing a small fudge of one trailing newline) — no-op.
    if block_start == anchor or abs(block_start - anchor) <= 1:
        return text, False

    block = text[block_start:block_end]
    # Strip leading/trailing newlines from block so we control spacing.
    block_inner = block.strip("\n")
    if anchor > block_start:
        # Block currently above where we want it — unusual; bail out.
        # (Don't shuffle the README in an unexpected direction.)
        return text, False

    # Remove block from its current position.
    new_text = text[:block_start] + text[block_end:]
    # Adjust anchor for the bytes we just removed.
    new_anchor = anchor
    if anchor > block_end:
        new_anchor -= (block_end - block_start)
    elif anchor > block_start:
        # Anchor was inside what we removed — shouldn't happen given guard
        # above, but bail just in case.
        return text, False

    # Insert block at new_anchor with two surrounding blank lines.
    before = new_text[:new_anchor].rstrip("\n") + "\n\n"
    after_part = new_text[new_anchor:].lstrip("\n")
    inserted = block_inner + "\n\n"
    new_text = before + inserted + after_part
    return new_text, True


def normalize(text: str) -> tuple[str, dict]:
    """Apply all three transformations. Returns (new_text, stats)."""
    stats = {"renames": 0, "moved_fields": False}
    text, n = apply_renames(text)
    stats["renames"] = n
    text, moved = move_fields_block(text)
    stats["moved_fields"] = moved
    return text, stats


def iter_readmes(only: list[Path]):
    if only:
        for p in only:
            readme = (ROOT / p / "README.md") if (ROOT / p / "README.md").exists() else (ROOT / p)
            if not readme.exists() or readme.suffix != ".md":
                print(f"skip: {p} (no README.md)")
                continue
            yield readme
        return
    for comp_py in ROOT.rglob("component.py"):
        if "__pycache__" in str(comp_py):
            continue
        readme = comp_py.parent / "README.md"
        if readme.exists():
            yield readme


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", nargs="*", default=[])
    ap.add_argument("--print-one", help="show before+after diff for one README and exit")
    args = ap.parse_args()

    if args.print_one:
        readme = (ROOT / args.print_one / "README.md") if (ROOT / args.print_one / "README.md").exists() else Path(args.print_one)
        old = readme.read_text()
        new, stats = normalize(old)
        print(f"# {readme.relative_to(ROOT)}")
        print(f"renames: {stats['renames']}, moved_fields: {stats['moved_fields']}")
        if old == new:
            print("(no changes)")
        else:
            import difflib
            diff = difflib.unified_diff(old.splitlines(keepends=True), new.splitlines(keepends=True), n=2)
            sys.stdout.writelines(diff)
        return

    only_paths = [Path(p) for p in args.only]
    counts = {"changed": 0, "unchanged": 0, "renamed_only": 0, "moved_only": 0, "both": 0}
    for readme in iter_readmes(only_paths):
        old = readme.read_text()
        new, stats = normalize(old)
        if old == new:
            counts["unchanged"] += 1
            continue
        counts["changed"] += 1
        if stats["renames"] > 0 and stats["moved_fields"]:
            counts["both"] += 1
        elif stats["renames"] > 0:
            counts["renamed_only"] += 1
        elif stats["moved_fields"]:
            counts["moved_only"] += 1
        if not args.dry_run:
            readme.write_text(new)

    for k, v in counts.items():
        print(f"{k:20} {v}")


if __name__ == "__main__":
    main()
