"""Regenerate the Fields section of every component README.

Reads each component.py, extracts Field() declarations (name, type, default,
description), buckets them into logical sections (Required / Connection /
Execution / Catalog metadata / Freshness / Partitions / Retry policy /
Other), and renders Markdown tables matching the precisely_run_asset
README's format.

Existing README prose is preserved. The generated block sits between two
markers:

    <!-- FIELDS:START - auto-generated by tools/regen_readme_fields.py -->
    ...
    <!-- FIELDS:END -->

If no markers exist yet, the block is inserted between the first H2 that
matches /^## Fields\b/ (if present) or just before the first '## Example'
heading. If neither anchor is found, the block is appended near the top of
the README right after the first paragraph.

Run:
    python3 tools/regen_readme_fields.py                 # regen all
    python3 tools/regen_readme_fields.py --dry-run       # diff-only
    python3 tools/regen_readme_fields.py --only PATH...  # specific dirs
"""
import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

START_MARKER = "<!-- FIELDS:START - auto-generated by tools/regen_readme_fields.py -->"
END_MARKER = "<!-- FIELDS:END -->"

# Bucket each field by name pattern. First-match wins, order matters.
# (label, regex)
SECTIONS = [
    ("Connection", re.compile(
        r"^(host|hostname|account|server|url|endpoint|base_url|port|user|username|"
        r"password|api_key|api_token|token|secret|client_id|client_secret|"
        r"private_key|private_key_file|private_key_file_pwd|public_key|"
        r"authenticator|warehouse|database|schema|catalog|role|"
        r"connection_string|connection_string_env_var|"
        r"resource_key|database_url_env_var)"
        r"(_env_var|_file|_pwd|_template)?$"
    )),
    ("Freshness", re.compile(r"^freshness_")),
    ("Partitions", re.compile(r"^partition_")),
    ("Retry policy", re.compile(r"^retry_")),
    ("Catalog metadata", re.compile(
        r"^(asset_key|key_prefix|asset_name|group_name|description|owners|"
        r"asset_tags|tags|kinds|deps|metadata|column_lineage|code_version|"
        r"automation_condition|backfill_policy|io_manager_key)$"
    )),
    ("Execution", re.compile(
        r"^(poll_interval_seconds|poll_seconds|timeout_seconds|timeout|"
        r"max_retries|retry_count|parameters|params|submit_path_template|"
        r"list_runs_path_template|path_template|api_version|api_path|"
        r"max_concurrency|max_workers|batch_size|chunk_size|page_size|"
        r"limit|offset|max_records|max_rows|max_messages|"
        r"warehouse|warehouse_size|wait_for_completion)$"
    )),
    ("Sensor configuration", re.compile(
        r"^(sensor_name|job_name|job_run_id|job_id|minimum_interval_seconds|"
        r"default_status|cursor|monitored_assets|monitored_jobs|"
        r"asset_selection|target)$"
    )),
    ("Source / target", re.compile(
        r"^(source_|target_|input_|output_|read_|write_|table|"
        r"table_name|target_table|source_table|target_database|source_database|"
        r"target_schema|source_schema|topic|queue|stream|bucket|prefix|"
        r"file_path|directory|format|mode|if_exists|partition_by|"
        r"sort_by|filter|filter_by|order_by|where|select)"
    )),
]


def parse_fields(py_path: Path) -> list[dict]:
    """Extract Field() declarations from a component.py via AST.

    Returns one dict per field with: name, type_str, default_str, description,
    required (bool), order (int — declaration order in source).
    """
    try:
        src = py_path.read_text()
        tree = ast.parse(src)
    except SyntaxError:
        return []

    fields: list[dict] = []
    # Walk only top-level classes that inherit from something component-like.
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        # Skip the Resource side-classes — only document the main Component.
        is_resource = any(
            (isinstance(b, ast.Attribute) and b.attr == "ConfigurableResource")
            or (isinstance(b, ast.Name) and b.id == "ConfigurableResource")
            for b in node.bases
        )
        if is_resource:
            continue
        # The component class typically has bases like (dg.Component, dg.Model, dg.Resolvable)
        bases_str = " ".join(ast.unparse(b) for b in node.bases)
        if "Component" not in bases_str and "Model" not in bases_str:
            continue

        for idx, item in enumerate(node.body):
            if not isinstance(item, ast.AnnAssign) or not isinstance(item.target, ast.Name):
                continue
            if item.value is None:
                continue
            # Look for `= Field(...)` calls
            if not (isinstance(item.value, ast.Call) and _is_field_call(item.value)):
                continue
            name = item.target.id
            if name.startswith("_"):
                continue
            type_str = ast.unparse(item.annotation)
            field_kwargs = {kw.arg: kw.value for kw in item.value.keywords if kw.arg}
            # Default
            default_node = field_kwargs.get("default")
            default_factory = field_kwargs.get("default_factory")
            if default_node is not None:
                default_str = _literal_str(default_node)
            elif default_factory is not None:
                default_str = f"`{ast.unparse(default_factory)}()`"
            else:
                # Required only if no default AND type isn't Optional
                default_str = None
            required = default_str is None and not _is_optional(type_str)
            # Description
            desc_node = field_kwargs.get("description")
            description = _literal_str(desc_node, raw=True) if desc_node is not None else ""
            description = description.replace("\n", " ").replace("|", "\\|").strip()
            description = re.sub(r"\s+", " ", description)
            fields.append({
                "name": name,
                "type_str": _clean_type(type_str),
                "default_str": default_str,
                "description": description,
                "required": required,
                "order": idx,
            })
        # Only take the first matching component class
        if fields:
            break
    return fields


def _is_field_call(call: ast.Call) -> bool:
    """Match `Field(...)`, `pydantic.Field(...)`, etc."""
    f = call.func
    if isinstance(f, ast.Name) and f.id == "Field":
        return True
    if isinstance(f, ast.Attribute) and f.attr == "Field":
        return True
    return False


def _literal_str(node: ast.AST, raw: bool = False) -> str:
    """Render a default-value or description AST node as a markdown-friendly string."""
    if isinstance(node, ast.Constant):
        v = node.value
        if v is None:
            return "—"
        if isinstance(v, bool):
            return f"`{str(v).lower()}`"
        if isinstance(v, (int, float)):
            return f"`{v}`"
        if isinstance(v, str):
            if raw:
                return v
            return f'`"{v}"`' if v else "—"
        return f"`{v!r}`"
    if isinstance(node, ast.List) and not node.elts:
        return "`[]`"
    if isinstance(node, ast.Dict) and not node.keys:
        return "`{}`"
    # For complex defaults, just unparse and backtick.
    return f"`{ast.unparse(node)}`"


def _is_optional(type_str: str) -> bool:
    """Optional[X] / X | None / Union[..., None]"""
    s = type_str.strip()
    if s.startswith("Optional[") or s.endswith("| None") or s.endswith("|None"):
        return True
    if "Union[" in s and ("None" in s or "NoneType" in s):
        return True
    return False


def _clean_type(t: str) -> str:
    """Shorten Optional[X] → X for readability (Default column already signals
    optionality)."""
    t = t.strip()
    m = re.match(r"^Optional\[(.+)\]$", t)
    if m:
        return m.group(1)
    # Strip trailing " | None"
    t = re.sub(r"\s*\|\s*None\s*$", "", t)
    return t


def bucket(fields: list[dict]) -> dict[str, list[dict]]:
    """Group fields by section. Required goes into its own bucket regardless
    of name."""
    buckets: dict[str, list[dict]] = {"Required": []}
    others: list[dict] = []
    for f in fields:
        if f["required"]:
            buckets["Required"].append(f)
        else:
            others.append(f)
    for f in others:
        for label, pattern in SECTIONS:
            if pattern.search(f["name"]):
                buckets.setdefault(label, []).append(f)
                break
        else:
            buckets.setdefault("Other", []).append(f)
    # Drop empty Required bucket if nothing landed there.
    if not buckets["Required"]:
        del buckets["Required"]
    return buckets


def render(buckets: dict[str, list[dict]]) -> str:
    """Render the markdown block. `Required` table has 3 cols (no Default),
    everything else has 4."""
    if not buckets:
        return ""
    out: list[str] = ["## Fields", ""]
    # Display order — matches the hand-curated precisely_run_asset format:
    # Required first, then connection, then execution-level tuning, then
    # catalog metadata, then freshness / partitions / retry / sensor /
    # source-target, with Other last for anything that didn't match a bucket.
    section_order = [
        "Required",
        "Connection",
        "Execution",
        "Catalog metadata",
        "Freshness",
        "Partitions",
        "Retry policy",
        "Sensor configuration",
        "Source / target",
        "Other",
    ]
    for label in section_order:
        rows = buckets.get(label)
        if not rows:
            continue
        # Sort within section by original declaration order for stability.
        rows.sort(key=lambda r: r["order"])
        out.append(f"### {label}")
        out.append("")
        if label == "Required":
            out.append("| Field | Type | Description |")
            out.append("|---|---|---|")
            for r in rows:
                out.append(
                    f"| `{r['name']}` | `{r['type_str']}` | {r['description'] or '—'} |"
                )
        else:
            out.append("| Field | Type | Default | Description |")
            out.append("|---|---|---|---|")
            for r in rows:
                default = r["default_str"] if r["default_str"] is not None else "—"
                out.append(
                    f"| `{r['name']}` | `{r['type_str']}` | {default} | {r['description'] or '—'} |"
                )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ── Splice the block into an existing README ───────────────────────────────


def splice(readme_text: str, block: str) -> str:
    """Insert/replace the FIELDS block in the README.

    Priority order:
      1. If START/END markers exist → replace what's between them
      2. If `## Fields` heading exists → replace from that heading until the next H2
      3. Else, insert just before the first `## Example` (or `## Examples`)
      4. Else, append to the end
    """
    wrapped = f"{START_MARKER}\n\n{block}\n{END_MARKER}"
    # Case 1: existing markers
    if START_MARKER in readme_text and END_MARKER in readme_text:
        return re.sub(
            re.escape(START_MARKER) + r"[\s\S]*?" + re.escape(END_MARKER),
            wrapped,
            readme_text,
        )
    # Case 2: existing `## Fields` heading — replace through next H2 or EOF
    m = re.search(r"^## Fields\b.*$", readme_text, re.MULTILINE)
    if m:
        next_h2 = re.search(r"^## ", readme_text[m.end():], re.MULTILINE)
        if next_h2:
            return (
                readme_text[: m.start()]
                + wrapped
                + "\n\n"
                + readme_text[m.end() + next_h2.start() :]
            )
        return readme_text[: m.start()] + wrapped + "\n"
    # Case 3: insert just before first `## Example` or `## Examples`
    m = re.search(r"^## Examples?\b", readme_text, re.MULTILINE)
    if m:
        return readme_text[: m.start()] + wrapped + "\n\n" + readme_text[m.start() :]
    # Case 4: append at end
    if not readme_text.endswith("\n"):
        readme_text += "\n"
    return readme_text + "\n" + wrapped + "\n"


# ── Driver ─────────────────────────────────────────────────────────────────


def iter_components(only: list[Path]):
    if only:
        for p in only:
            comp_py = (ROOT / p / "component.py") if (ROOT / p / "component.py").exists() else p
            if not comp_py.exists():
                print(f"skip: {p} (no component.py)")
                continue
            yield comp_py
        return
    for comp_py in ROOT.rglob("component.py"):
        if "__pycache__" in str(comp_py):
            continue
        yield comp_py


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="print summary without writing files")
    ap.add_argument("--only", nargs="*", default=[], help="restrict to these component paths (relative to repo root)")
    ap.add_argument("--print-one", help="print rendered block for a single component path, then exit")
    args = ap.parse_args()

    if args.print_one:
        comp_py = (ROOT / args.print_one / "component.py") if (ROOT / args.print_one / "component.py").exists() else Path(args.print_one)
        fields = parse_fields(comp_py)
        print(render(bucket(fields)))
        return

    only_paths = [Path(p) for p in args.only]
    stats = {"changed": 0, "unchanged": 0, "skipped_no_readme": 0, "skipped_no_fields": 0, "errored": 0}
    changed_paths: list[str] = []
    for comp_py in iter_components(only_paths):
        readme = comp_py.parent / "README.md"
        if not readme.exists():
            stats["skipped_no_readme"] += 1
            continue
        try:
            fields = parse_fields(comp_py)
        except Exception as e:
            print(f"  error parsing {comp_py.relative_to(ROOT)}: {e}", file=sys.stderr)
            stats["errored"] += 1
            continue
        if not fields:
            stats["skipped_no_fields"] += 1
            continue
        block = render(bucket(fields))
        old = readme.read_text()
        new = splice(old, block)
        if old == new:
            stats["unchanged"] += 1
            continue
        stats["changed"] += 1
        changed_paths.append(str(comp_py.parent.relative_to(ROOT)))
        if not args.dry_run:
            readme.write_text(new)

    print(f"changed:           {stats['changed']}")
    print(f"unchanged:         {stats['unchanged']}")
    print(f"skipped (no md):   {stats['skipped_no_readme']}")
    print(f"skipped (no flds): {stats['skipped_no_fields']}")
    print(f"errored:           {stats['errored']}")
    if args.dry_run and changed_paths:
        print(f"\nFirst 20 would-be changes:")
        for p in changed_paths[:20]:
            print(f"  {p}")


if __name__ == "__main__":
    main()
